import { format } from 'd3-format';
import { range } from 'd3-array';

export const COLORS = {
  blue: '#2588ac',
  darkRed: '#8F0A09',
  mediumRed: '#b2201f',
  lightRed: '#d84544',
  darkGray: '#343131',
  grayLighter: '#f2f2f2',
  gray: '#f1f4f4',
  mediumGray: '#ccd3d3',
  white: '#fff',
  black: '#000',
  headerColor: '#fcefea',
};
export const ALL_YEARS = 'All Years';

export const SPEED = 1.4;

export const COMMA_FORMATTER = format(',.0f');

export const REGION_LOOKUP = new Map([
  ['Honduras', 'Central America'],
  ['Cuba', 'Central America'],
  ['Guatemala', 'Central America'],
  ['El Salvador', 'Central America'],
  ['Jamaica', 'Central America'],
  ['Haiti', 'Central America'],
  ['Afghanistan', 'Central Asia'],
  ['Uzbekistan', 'Central Asia'],
  ['Kazakhstan', 'Central Asia'],
  ['Turkmenistan', 'Central Asia'],
  ['Kyrgyzstan', 'Central Asia'],
  ['Tajikistan', 'Central Asia'],
  ['China', 'East Asia'],
  ['Mongolia', 'East Asia'],
  ['Ukraine', 'Eastern Europe'],
  ['Serbia', 'Eastern Europe'],
  ['Turkey', 'Eastern Europe'],
  ['Armenia', 'Eastern Europe'],
  ['Belarus', 'Eastern Europe'],
  ['Bulgaria', 'Eastern Europe'],
  ['Azerbaijan', 'Eastern Europe'],
  ['Latvia', 'Eastern Europe'],
  ['Georgia', 'Eastern Europe'],
  ['Lithuania', 'Eastern Europe'],
  ['Estonia', 'Eastern Europe'],
  ['Croatia', 'Eastern Europe'],
  ['Iraq', 'Middle East'],
  ['Jordan', 'Middle East'],
  ['United Arab Emirates', 'Middle East'],
  ['Lebanon', 'Middle East'],
  ['Kuwait', 'Middle East'],
  ['Yemen', 'Middle East'],
  ['Saudi Arabia', 'Middle East'],
  ['Djibouti', 'Middle East'],
  ['Israel', 'Middle East'],
  ['Oman', 'Middle East'],
  ['Algeria', 'North Africa'],
  ['Egypt', 'North Africa'],
  ['Tunisia', 'North Africa'],
  ['Libya', 'North Africa'],
  ['Morocco', 'North Africa'],
  ['Canada', 'North America'],
  ['Colombia', 'South America'],
  ['Ecuador', 'South America'],
  ['Pakistan', 'South Asia'],
  ['India', 'South Asia'],
  ['Nepal', 'South Asia'],
  ['Bhutan', 'South-East Asia'],
  ['Cambodia', 'South-East Asia'],
  ['Bangladesh', 'South-East Asia'],
  ['Indonesia', 'South-East Asia'],
  ['Thailand', 'South-East Asia'],
  ['Malaysia', 'South-East Asia'],
  ['Philippines', 'South-East Asia'],
  ['New Zealand', 'South-East Asia'],
  ['Somalia', 'Sub-Saharan Africa'],
  ['Ethiopia', 'Sub-Saharan Africa'],
  ['Burundi', 'Sub-Saharan Africa'],
  ['Central African Republic', 'Sub-Saharan Africa'],
  ['Eritrea', 'Sub-Saharan Africa'],
  ['Rwanda', 'Sub-Saharan Africa'],
  ['Sudan', 'Sub-Saharan Africa'],
  ['Congo', 'Sub-Saharan Africa'],
  ['Guinea', 'Sub-Saharan Africa'],
  ['Liberia', 'Sub-Saharan Africa'],
  ['Uganda', 'Sub-Saharan Africa'],
  ['Cameroon', 'Sub-Saharan Africa'],
  ['Chad', 'Sub-Saharan Africa'],
  ['Senegal', 'Sub-Saharan Africa'],
  ['Sierra Leone', 'Sub-Saharan Africa'],
  ['Togo', 'Sub-Saharan Africa'],
  ['Equatorial Guinea', 'Sub-Saharan Africa'],
  ['Gabon', 'Sub-Saharan Africa'],
  ['South Africa', 'Sub-Saharan Africa'],
  ['Kenya', 'Sub-Saharan Africa'],
  ['Zimbabwe', 'Sub-Saharan Africa'],
  ['Gambia', 'Sub-Saharan Africa'],
  ['Nigeria', 'Sub-Saharan Africa'],
  ['Mali', 'Sub-Saharan Africa'],
  ['Mauritania', 'Sub-Saharan Africa'],
  ['Malawi', 'Sub-Saharan Africa'],
  ['Angola', 'Sub-Saharan Africa'],
  ['Ghana', 'Sub-Saharan Africa'],
  ['Niger', 'Sub-Saharan Africa'],
  ['Botswana', 'Sub-Saharan Africa'],
  ['Benin', 'Sub-Saharan Africa'],
  ['Namibia', 'Sub-Saharan Africa'],
  ['Zambia', 'Sub-Saharan Africa'],
  ['Sweden', 'Western Europe'],
  ['Norway', 'Western Europe'],
  ['Netherlands', 'Western Europe'],
  ['Belgium', 'Western Europe'],
  ['Burma', 'South-East Asia'],
  ['Vietnam', 'South-East Asia'],
  ['Dem. Rep. Congo', 'Sub-Saharan Africa'],
  ['Iran', 'Middle East'],
  ['Ivory Coast', 'Sub-Saharan Africa'],
  ['Palestine', 'Middle East'],
  ['Republic of South Sudan', 'Sub-Saharan Africa'],
  ['Russia', 'Eastern Europe'],
  ['Moldova', 'Eastern Europe'],
  ['Korea, North', 'East Asia'],
  ['Syria', 'Middle East'],
  ['Sri Lanka (Ceylon)', 'South-East Asia'],
  ['Laos', 'South-East Asia'],
  ['Gaza Strip', 'Middle East'],
  ['Tibet', 'East Asia'],
  ['United Kingdom', 'Western Europe'],
  ['Tanzania', 'Sub-Saharan Africa'],
  ['Venezuela', 'South America'],
  ['Guinea - Bissau', 'Sub-Saharan Africa'],
  ['Burkina Faso (UVolta)', 'Sub-Saharan Africa'],
]);

export const SIDEBAR_WIDTH = 510;

export const DEFAULT_VIEWPORT = {
  latitude: 39.8283459,
  longitude: -98.5794797,
  zoom: 4,
  bearing: 0,
  pitch: 0,
};

export const LAYER_ID = 'circles';
export const MIN_YEAR = 2010;
export const MAX_YEAR = 2020;
export const YEARS = range(MIN_YEAR, MAX_YEAR + 1);

export const MIN_RADIUS = 5;
export const MAX_RADIUS = 25;
export const CIRCLE_OPACITY = 0.7;
